name: Build React App

on:
  workflow_call:
    inputs:
      node_version:
        default: '22'
        required: true
        type: string

jobs:
  build-react:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Cache Node.js Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-${{ runner.os }}-${{ inputs.node_version }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            node-${{ runner.os }}-

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install Dependencies
        run: yarn install

      - name: Build Project
        run: yarn build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: react-build
          path: dist
