name: Build React App

on:
  workflow_call:
    inputs:
      node_version:
        default: '22'
        required: true
        type: string
    secrets:
      DEV_API_BASE_URL:
        required: true
      DEV_GOOGLE_MAPS_API_KEY:
        required: true
      DEV_GOOGLE_MAP_ID:
        required: true
      PROD_API_BASE_URL:
        required: true
      PROD_GOOGLE_MAPS_API_KEY:
        required: true
      PROD_GOOGLE_MAP_ID:
        required: true

jobs:
  build-react:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Cache Node.js Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-${{ runner.os }}-${{ inputs.node_version }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            node-${{ runner.os }}-

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}

      - name: Create Environment File
        run: |
          if [[ "$GITHUB_REF" == "refs/heads/master" ]]; then
            echo "VITE_GOOGLE_MAPS_API_KEY=${{ secrets.PROD_GOOGLE_MAPS_API_KEY }}" >> .env
            echo "VITE_GOOGLE_MAP_ID=${{ secrets.PROD_GOOGLE_MAP_ID }}" >> .env
            echo "VITE_API_BASE_URL=${{ secrets.PROD_API_BASE_URL }}" >> .env
          else
            echo "VITE_GOOGLE_MAPS_API_KEY=${{ secrets.DEV_GOOGLE_MAPS_API_KEY }}" >> .env
            echo "VITE_GOOGLE_MAP_ID=${{ secrets.DEV_GOOGLE_MAP_ID }}" >> .env
            echo "VITE_API_BASE_URL=${{ secrets.DEV_API_BASE_URL }}" >> .env
          fi

      - name: Validate .env File
        run: cat .env

      - name: Install Dependencies
        run: yarn install

      - name: Build Project
        run: yarn build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: react-build
          path: dist
