name: Pull Request Workflow

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    with:
      node_version: '22'
    secrets:
      DEV_API_BASE_URL: ${{ secrets.DEV_API_BASE_URL }}
      DEV_GOOGLE_MAPS_API_KEY: ${{ secrets.DEV_GOOGLE_MAPS_API_KEY }}
      DEV_GOOGLE_MAP_ID: ${{ secrets.DEV_GOOGLE_MAP_ID }}
      PROD_API_BASE_URL: ${{ secrets.PROD_API_BASE_URL }}
      PROD_GOOGLE_MAPS_API_KEY: ${{ secrets.PROD_GOOGLE_MAPS_API_KEY }}
      PROD_GOOGLE_MAP_ID: ${{ secrets.PROD_GOOGLE_MAP_ID }}

  snyk-scan:
    name: Snyk Vulnerability Scan
    uses: ./.github/workflows/snyk-analysis.yaml
    secrets: inherit
