name: Pull Request Workflow

on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    with:
      node_version: '22'

  snyk-scan:
    name: Snyk Vulnerability Scan
    uses: ./.github/workflows/snyk-analysis.yaml
    secrets: inherit
